service: tlsposture

frameworkVersion: "^3.23.0"

provider:
  name: aws
  runtime: provided.al2
  region: eu-west-2

package:
  individually: true

functions:
  hello:
    handler: bootstrap
    package:
      artifact: bin/hello.zip
    events:
      - httpApi:
          path: /hello
          method: get
  ssllabs:
    handler: bootstrap
    package:
      artifact: bin/ssllabs.zip

stepFunctions:
  stateMachines:
    hellostepfunc1:
      tracingConfig:
        enabled: true
      events:
        - http:
            path: gofunction
            method: GET
        - schedule:
            rate: rate(10 minutes)
            enabled: true
            input:
              key1: value1
              key2: value2
              stageParams:
                stage: dev
      name: myStateMachine
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            End: true
  validate: true

resources:
  Resources:
    HostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: host
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: host
            AttributeType: S

plugins:
  - serverless-better-credentials # as the first plugin
  - serverless-step-functions
